### ISSUE TITLE
(Docker) ARM architecture not supported by this script

### ISSUE THREAD

**Issue by Zlendy** [RayNieport/mconBot#1]
I have tried to run this script with Docker on my Raspberry Pi only to find out that apparently "it is not supported".
![image](https://user-images.githubusercontent.com/22578704/119244553-25d03500-bb72-11eb-9b0a-b62597306c58.png)
However, when I clone the repository and execute it manually everything seems to work well.

**Comment by RayNieport** [comment]
Thanks for testing! I have a Pi as well, but I've only tested the Docker image on x86 machines so far. This must be some issue with the way I created the Docker image, because Python and all the other dependencies should run fine on ARM. I'll load it up on my Pi this week and see if I can create a working Docker image to support the ARM architecture.

**Comment by RayNieport** [comment]
Okay, the Docker image should now support arm64. I was originally using the 'python:3.8-slim' base image, but I encountered some issues when compiling and had to swap to the 'alpine:3.13' base instead. I'll update the Dockerfile shortly to reflect my changes.

Would you mind pulling to make sure everything works now? I tested on my Pi 3B+ but it's always nice to a second set of eyes.

**Comment by Zlendy** [comment]
As expected, it's working now. I would also suggest you to add tags to indicate the architectures that are supported.
